---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: testchat-1-oct4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testchat-1-oct4 
  name: testchat-1-oct4
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi